#!/usr/bin/env bash
# Install a deliberately maximal sudoers policy for destructive boundary tests.
#
# This is NOT a production policy. It grants the kyagent runtime account full
# passwordless root access so every tool can be tested at the permission limit.
#
# Usage (root required):
#   sudo bash scripts/setup-sudoers-max-test.sh
#   sudo bash scripts/setup-sudoers-max-test.sh --yes
set -euo pipefail

USER_NAME=${KYAGENT_USER:-kyagent}
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
SETUP_SUDOERS="$SCRIPT_DIR/setup-sudoers.sh"
SUDOERS_DST="/etc/sudoers.d/kyagent"
BACKUP=""
TMP_SUDOERS=""
ASSUME_YES=0

cleanup() {
  [[ -n "$TMP_SUDOERS" && -f "$TMP_SUDOERS" ]] && rm -f "$TMP_SUDOERS"
  return 0
}
trap cleanup EXIT

die() {
  echo "[!] $*" >&2
  exit 1
}

for arg in "$@"; do
  case "$arg" in
    -y|--yes) ASSUME_YES=1 ;;
    *) die "未知参数：$arg" ;;
  esac
done

confirm() {
  echo "[kyagent][MAX-TEST] 将为账户 '${USER_NAME}' 写入最大测试 sudoers："
  echo "  目标文件:     ${SUDOERS_DST}"
  echo "  授权范围:     ${USER_NAME} ALL=(ALL:ALL) NOPASSWD:SETENV: ALL"
  echo "  含义:         可免密以任意用户/组运行任意命令，并允许保留/设置环境变量"
  echo "  用途:         全部工具、权限极限、安全护栏极限测试"
  echo "  禁止用途:     生产、演示正式安全模型、联网未知任务、长期保留"
  echo
  echo "[kyagent][MAX-TEST] 恢复正常最小权限：sudo bash scripts/setup-sudoers.sh"
  echo "[kyagent][MAX-TEST] 恢复生产预设权限：sudo bash scripts/setup-sudoers-prod.sh --yes"
  echo

  if [[ "$ASSUME_YES" -eq 1 ]]; then
    return 0
  fi
  if [[ ! -t 0 ]]; then
    die "非交互环境必须显式加 --yes 确认极限测试授权"
  fi

  local reply
  read -r -p "确认写入最大测试 sudoers？这等价于给 ${USER_NAME} 完整 root 权限。[y/N] " reply
  case "$reply" in
    y|Y|yes|YES) ;;
    *) echo "[kyagent] 已取消。"; exit 0 ;;
  esac
}

render_sudoers() {
  local user_name="$1"
  cat <<EOF
# /etc/sudoers.d/kyagent
#
# MAX-TEST sudoers generated by scripts/setup-sudoers-max-test.sh.
# This file is intentionally broader than the normal kyagent sudoers policy.
# Do not use in production. Revert with:
#   sudo bash scripts/setup-sudoers.sh
# or the production preset:
#   sudo bash scripts/setup-sudoers-prod.sh --yes

Defaults:${user_name}  !visiblepw, lecture=never, !requiretty, log_input, log_output, \
                       iolog_dir=/var/log/sudo-io/%{user}, setenv

${user_name}  ALL=(ALL:ALL)  NOPASSWD:SETENV: ALL
EOF
}

main() {
  if [[ $EUID -ne 0 ]]; then
    die "此脚本需要 root；请执行 sudo bash scripts/setup-sudoers-max-test.sh"
  fi
  command -v visudo >/dev/null 2>&1 || die "找不到 visudo，请先安装 sudo 包"

  if [[ ! "$USER_NAME" =~ ^[a-z_][a-z0-9_-]{0,31}$ ]]; then
    die "非法运行账户名：$USER_NAME"
  fi

  confirm

  if ! id "$USER_NAME" >/dev/null 2>&1; then
    echo "[+] 创建系统账户 $USER_NAME"
    local nologin="/usr/sbin/nologin"
    [[ -x "$nologin" ]] || nologin="/sbin/nologin"
    useradd -r -s "$nologin" -m -d "/var/lib/$USER_NAME" "$USER_NAME"
  fi

  TMP_SUDOERS="$(mktemp)"
  render_sudoers "$USER_NAME" >"$TMP_SUDOERS"
  chmod 0440 "$TMP_SUDOERS"

  if ! visudo -cf "$TMP_SUDOERS"; then
    die "sudoers 临时文件语法校验失败，未写入 $SUDOERS_DST"
  fi

  if [[ -f "$SUDOERS_DST" ]]; then
    BACKUP="$(mktemp)"
    cp -p "$SUDOERS_DST" "$BACKUP"
  fi

  install -m 0440 "$TMP_SUDOERS" "$SUDOERS_DST"
  if ! visudo -cf "$SUDOERS_DST"; then
    echo "[!] sudoers 安装后校验失败，开始回滚" >&2
    if [[ -n "$BACKUP" && -f "$BACKUP" ]]; then
      install -m 0440 "$BACKUP" "$SUDOERS_DST"
    else
      rm -f "$SUDOERS_DST"
    fi
    [[ -n "$BACKUP" ]] && rm -f "$BACKUP"
    exit 2
  fi
  [[ -n "$BACKUP" ]] && rm -f "$BACKUP"

  mkdir -p /var/log/sudo-io
  chmod 0700 /var/log/sudo-io
  install -d -m 0700 -o "$USER_NAME" -g "$USER_NAME" "/var/lib/kyagent"
  install -d -m 0700 -o "$USER_NAME" -g "$USER_NAME" /var/log/kyagent

  if [[ -f "$SETUP_SUDOERS" ]]; then
    # shellcheck source=/dev/null
    source "$SETUP_SUDOERS"
    install_all_kyagent_wrappers
  fi

  echo "[OK] kyagent 最大测试 sudoers 已安装。"
  echo "    账户:        $USER_NAME"
  echo "    sudoers:     $SUDOERS_DST"
  echo "    恢复最小权限: sudo bash scripts/setup-sudoers.sh"
  echo "    恢复生产预设: sudo bash scripts/setup-sudoers-prod.sh --yes"
}

if [[ "${BASH_SOURCE[0]}" == "$0" ]]; then
  main "$@"
fi
